name: Build
run-name: ${{ gitea.actor }} is cooking
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t registery.toadonload.ru/garden:latest
      - name: Push
        run: docker push registery.toadonload.ru/garden:latest
